### ISSUE TITLE
detect shipping line using BIC code

### ISSUE THREAD

**Issue by shimarisuu** [bic-org/Boxtech#17]
Hi. I would like to know if there's any available database or JSON file containing BIC code/shipping line(company) pairs. 

I've tried to use web scraping on this website _https://www.bic-code.org/bic-letter-search/_ to retrieve such data but I always get "403 Forbidden" error. Is it a private information or something like that?

**Comment by cmsdroff** [comment]
@akinariobi Thanks for raising an issue, I was just wondering what is the use case for your query?

Containers can be owned by the carrier/shipping line OR by a leasing company who hire them to carriers (this changes)

Are you trying to identify the carrier OR the owner of the container?

**Comment by cmsdroff** [comment]
@akinariobi the data you are looking for is probably in the API which is always better than scraping, you just need to register to use.  This may suit your needs?  some responses may show the lease company (rather than who its on lease to) so just to be aware.

example output from JSON response

```json
"codeholder": "CMA-CGM",
"container_number": “CMAU5841972"
```

API details: https://github.com/bic-boxtech/BIC-BoxTech-API-Samples

Hope this helps?  If so can we close the issue?

**Comment by shimarisuu** [comment]
@cmsdroff Thanks for your reply. I'm trying to identify the carrier. 
Yes, let's close it.
